# EX1

In [1]:
from array import *
A=array('i',[1,2,3,4,5,6,7,8,9])
x=A.tolist()
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


# EX2

In [3]:
import numpy as np
sum=0
A= np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(A)
for i in range (3):
  for j in range (3):
    if i == j :
      sum+=A[i][j]
print("diagonal",sum)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
diagonal 15


# EX3

In [4]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6],[13,14]])
arr = np.array([[7,8],[9,10],[11,12],[15,16]])
def high(arr,a):
    k=[]
    for i in range(len(arr)):
        for j in range(len(arr[i])):
            if(arr[i][j] > a):
                k.append(arr[i][j])
    return k
print(high(arr,11))
print(high(a,5))

[12, 15, 16]
[6, 13, 14]


# EX4

In [5]:
import numpy as np
A = np.array([[1,2],[3,4],[5,6],[13,14]])
B = np.array([[7,8],[9,10],[11,12],[15,16]])
c=[]
def summ(A,B,c):
  if A.shape == B.shape :
    c.append(A+B)
    return c
l=summ(A,B,c)
print(l)

[array([[ 8, 10],
       [12, 14],
       [16, 18],
       [28, 30]])]


# EX5

In [15]:
import numpy as np
A = np.array([[1,2],[3,4],[5,6],[13,14]])
arr = []
for i in range(len(a)):
    l = []
    for j in range(len(a[i])):
        l.append(a[i][j])
    tot = 0
    for k in range(len(l)):
        tot+= l[k]
    tot = tot/len(l)
    arr.append(tot)
print(arr)

[1.5, 3.5, 5.5, 13.5]
